# -*- coding: utf-8 -*-
"""ResultGrandTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LwGiFOTGPjzL15dt9_69j8UVSdpg32J

## Initialisation générale

### Dépendances
"""
import sys
sys.path.append('../py_programs/')

# Modules python a importer :
# Classes
from classEnergyAnalyzer import EnergyAnalyzer
from classPyTorchModel import pyTorchModel
from classDatasets import Dataset
from CSVReader import CSVfile

# Modules
import classModelTester as Tester
import DataTools

# Librairies externes
import torchvision
import torchvision.models as ExampleModels
import matplotlib.pyplot as plt

"""### Initialisation des variables"""

analyzer = EnergyAnalyzer("testPytorch", name_output_file="./testgeneral.csv")
analyzer.recup_file_result()
file_analysis = analyzer.csvResult
list_model = DataTools.models.list_models(module=ExampleModels)
print(list_model)

"""## Traitement des résultats

### Préparation des fichiers dans un répertoire temporaire
"""

'''!cd /content/
!ls
!mkdir csv_result
!rm -rf ./csv_result/*.csv
!cp ./*.csv csv_result/'''

"""### Retranscription des résultats

#### extraction des resultats
"""

#get id from the column project_name
worked_models_parameters = []
list_id_worked_models = []
list_total_layer = []
all_labels_models = []

col_project_name = file_analysis.get_column("project_name")
for line in col_project_name:
  label_model = line.split("CollabLinux:train:CollabLinux(")[1]
  for i in range(len(list_model)):
    if list_model[i]==label_model:
      list_id_worked_models.append(i)
      break


for id_model in list_id_worked_models :
  m=DataTools.models.get_model(str(list_model[id_model]))
  all_labels_models.append(str(list_model[id_model]))
  worked_models_parameters.append(sum(p.numel() for p in m.parameters()))
  list_total_layer.append(sum(1 for l in  m.named_modules()))
  
 

"""#### On construit un dictionnaire avec les paramètres pyTorch des modèles"""

dict_models = []
for i in range(len(all_labels_models )):
  dic = {}

  #Add property to the models here
  dic["param"] = worked_models_parameters[i]
  dic["total_param"] = worked_models_parameters[i]
  dic["name"] = all_labels_models[i]
  dic["total_layers"] = list_total_layer[i]

  dict_models.append(dic)

# Mettre ici les colonnes codecarbon de l'ancien fichier à copier dans le nouveau fichier
cols_conserver = ["duration", "gpu_power"]

#necessaire pour l'étude graphique plus bas
mandatory_col = ["energy_consumed"]
save_columns = mandatory_col + cols_conserver
project_column = ["project_name"]

#label de la machine qui a fait les operations
label_Machine = "ordiTsp"
col_label_machine = [label_Machine for i in range(len(dict_models))]

'''#label du type de calcul actuel
label_operation = "number_parameters"
col_label_operation = [label_operation for i in range(len(save_columns))]
'''
cols_result_analyze = analyzer.csvResult.extract_data(save_columns)

#écriture des colonnes de codecarbon dans le dictionnaire
for key in range(len(save_columns)) :
  for i in range(len(dict_models)):
    dict_models[i][save_columns[key]] = cols_result_analyze[key][i]

"""### On conserve les éléments importants dans un autre fichier csv"""

resultFile =  CSVfile.create_file("./result.csv")
resultFile.add_column("label_machine", col_label_machine)
#resultFile.add_column("label_operation", col_label_operation)
#resultFile.add_columns(save_columns, cols_result_analyze)

def get_column(list_dic,label_key):
  l = []
  for i in range(len(list_dic)):
      l.append(list_dic[i][label_key])
  return l

def to_float(l):
  new_list = []
  for e in l:
    new_list.append(float(e))
  return new_list




print(dict_models)
for key in dict_models[0].keys():
  print(key)
  resultFile.add_column(key, get_column(dict_models, key))

resultFile.write_data_to_file()

"""## Présentation des résultats

### Evaluation des émissions des modèles

##### unsorted
"""

plt.plot(get_column(dict_models, "total_param"), to_float(get_column(dict_models, "energy_consumed")), '+')
plt.xlabel("nombre paramètres")
plt.ylabel("eq kg/CO2")
#plot("test1", "test2",get_column(dict_models, "total_param"), get_column(dict_models, "energy_consumed") )
plt.suptitle("emissions by numbers of parameters")
plt.legend()
plt.show()

#dict(sorted(dict_models, key=lambda item: item["total_param"]))
dict_models.sort(key=lambda item: item["name"])

sorted_emissions_per_param = [(a["name"],a["total_param"], a["energy_consumed"]) for a in dict_models]


print(sorted_emissions_per_param)

plt.plot(get_column(dict_models, "total_param"), to_float(get_column(dict_models, "energy_consumed")), '+')
plt.xlabel("nombre paramètres")
plt.ylabel("eq kg/CO2")
#plot("test1", "test2",get_column(dict_models, "total_param"), get_column(dict_models, "energy_consumed") )
plt.suptitle("emissions by numbers of parameters")
plt.legend()
plt.show()

dict_models.sort(key=lambda item: item["total_layers"])
sorted_emissions_per_layers = [(a["name"],a["total_layers"], float(a["energy_consumed"])) for a in dict_models]
print(sorted_emissions_per_layers)

dict_models2 = dict_models[:len(dict_models)-2]
plt.plot((get_column(dict_models2, "total_layers")), to_float(get_column(dict_models2, "energy_consumed")), '+')
plt.xlabel("nombre de couches")
plt.ylabel("eq kg/CO2")
#plot("test1", "test2",get_column(dict_models, "total_layers"), get_column(dict_models, "energy_consumed") )
plt.suptitle("emissions by numbers of layers")
plt.legend()
plt.show()

dict_models.sort(key=lambda item: item["total_layers"])
sorted_emissions_per_layers = [(a["name"],a["total_layers"], float(a["duration"])) for a in dict_models]
print(sorted_emissions_per_layers)

dict_models2 = dict_models[:len(dict_models)-2]
plt.plot(to_float(get_column(dict_models2, "total_layers")), to_float(get_column(dict_models2, "duration")), '+')
plt.xlabel("nombre de couches")
plt.ylabel("eq kg/CO2")
#plot("test1", "test2",get_column(dict_models, "total_layers"), get_column(dict_models, "energy_consumed") )
plt.suptitle("emissions by numbers of layers")
plt.legend()
plt.show()

dict_models.sort(key=lambda item: item["total_layers"])
sorted_emissions_per_layers = [(a["name"],a["total_layers"], float(a["duration"])) for a in dict_models]
print(sorted_emissions_per_layers)

dict_models2 = dict_models[:len(dict_models)-2]
plt.plot(to_float(get_column(dict_models2, "total_layers")), to_float(get_column(dict_models2, "gpu_power")), '+')
plt.xlabel("nombre de couches")
plt.ylabel("eq kg/CO2")
#plot("test1", "test2",get_column(dict_models, "total_layers"), get_column(dict_models, "energy_consumed") )
plt.suptitle("emissions by numbers of layers")
plt.legend()
plt.show()

"""### Evaluations des performances des modeles

#### Calcul des performances
"""

indices_to_skip = []
list_ratio_performances = []
for i in range(len(all_labels_models)) :
  m = pyTorchModel.createPyTorchNet(DataTools.usual_criterion, 3) # on ilporte un autre modele apres donc pas impportant (TODO corriger pr ne plus faire ca)
  try :
    path = "./data_gathered/all_pth/"+str(all_labels_models[i])+".pth"
    print("test output on ", path)
    correct_predictions, total_predictions = m.analyse_performance(path, DataTools.CIFAR10.test_inputs, DataTools.usual_classes)
    correct,total= m.get_global_performance(correct_predictions, total_predictions)

  except :
    print("failed")
    indices_to_skip.append(i)
    list_ratio_performances.append(-1)

    continue
  list_ratio_performances.append(correct/total)
print("Modele not found for ", indices_to_skip)

for i in range(len(dict_models)):
    dict_models[i]["ratio_perf"] = list_ratio_performances[i]

resultFile.add_column("ratio_perf", list_ratio_performances)
resultFile.write_data_to_file()

print(list_ratio_performances)

#ajustement de la valeur "Null" pour mieux voir l'ecart des valeurs
for element in dict_models:
  if element["ratio_perf"]==-1:
    element["ratio_perf"] = 0

"""#### Résultats des performances"""

dict_models.sort(key=lambda item: item["total_param"])
sorted_perf_per_param = [(a["name"],a["total_param"], a["ratio_perf"]) for a in dict_models]
print(sorted_perf_per_param)

plt.plot(to_float(get_column(dict_models, "total_param")), to_float(get_column(dict_models, "ratio_perf")), '+')
plt.xlabel("nombre de paramètres")
plt.ylabel("ratio performances")
#plot("test1", "test2",get_column(dict_models, "total_param"), get_column(dict_models, "ratio_perf") )
plt.suptitle("performance par nombres de parametres")
plt.legend()
plt.show()

dict_models.sort(key=lambda item: item["total_layers"])
sorted_perf_per_layers = [(a["name"],a["total_layers"], a["ratio_perf"]) for a in dict_models]
print(sorted_perf_per_layers)

plt.plot(get_column(dict_models, "total_layers"), get_column(dict_models, "ratio_perf"), '+')
plt.xlabel("nombre de couches")
plt.ylabel("ratio performances")
#plot("test1", "test2",get_column(dict_models, "total_layers"), get_column(dict_models, "ratio_perf") )
plt.suptitle("perf par nombres de couches")
plt.legend()
plt.show()